acbeo/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("trainings/", include("trainings.urls")),
    path("berichte/", include("bookkeeping.urls")),
    path("", include("news.urls")),
]

news/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views


urlpatterns = [
    path("", views.PostListView.as_view(), name="home"),
    path("kontakt/", views.ContactFormView.as_view(), name="contact"),
    path("registrieren/", views.PilotCreateView.as_view(), name="register"),
    path("mitglied-werden/", views.MembershipFormView.as_view(), name="membership"),
    path("anmelden/", LoginView.as_view(template_name="news/login.html"), name="login"),
    path("konto-bearbeiten/", views.PilotUpdateView.as_view(), name="update_pilot"),
    path("abmelden/", LogoutView.as_view(), name="logout"),
    path(
        "passwort-zuruecksetzen/",
        views.PilotPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "passwort-zuruecksetzen/<uidb64>/<token>/",
        views.PilotPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("<slug:slug>/", views.PostDetailView.as_view(), name="post"),
]

news/models.py
from django.conf import settings
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.utils.timezone import now


class Post(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="posts"
    )
    content = models.TextField()
    created_on = models.DateTimeField(default=now)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title


class PilotManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError("Pilot must have an email address")

        pilot = self.model(email=self.normalize_email(email))

        pilot.set_password(password)
        pilot.save()
        return pilot

    def create_superuser(self, email, password=None):
        pilot = self.create_user(
            email,
            password=password,
        )
        pilot.role = Pilot.Role.STAFF
        pilot.save()
        return pilot


def validate_phone(phone):
    for character in phone:
        if character not in "0123456789+() ":
            raise ValidationError(
                f"{phone} ist keine Telefonnummer.", params={"phone": phone}
            )


class Pilot(AbstractBaseUser):
    Role = models.IntegerChoices("Role", "GUEST MEMBER ORGA STAFF")

    email = models.EmailField(max_length=255, unique=True)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    phone = models.CharField(max_length=20, validators=[validate_phone])
    date_joined = models.DateTimeField(auto_now_add=True)
    role = models.IntegerField(choices=Role.choices, default=Role.GUEST)
    prepaid_flights = models.DecimalField(
        max_digits=5, decimal_places=2, validators=[MinValueValidator(0)], default=0
    )
    is_new = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)

    objects = PilotManager()

    USERNAME_FIELD = "email"

    class Meta:
        ordering = ["first_name", "last_name"]

    def __str__(self):
        return self.first_name + " " + self.last_name

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def make_member(self):
        self.role = self.Role.MEMBER
        self.save()

    @property
    def is_member(self):
        return self.role >= self.Role.MEMBER

    @property
    def is_orga(self):
        return self.role >= self.Role.ORGA

    @property
    def is_staff(self):
        return self.role == self.Role.STAFF

    @property
    def short_name(self):
        MAX_LENGTH = 15
        if len(name := str(self)) <= MAX_LENGTH:
            return name

        first, *middle_names, last = name.split()
        for i, name in enumerate(middle_names):
            if name in ["von", "Von"]:
                middle_names[i] = "v."
        
        short_name = " ".join([first] + middle_names + [last])
        if len(short_name) <= MAX_LENGTH:
            return short_name
        
        short_name = short_name[:MAX_LENGTH - 1] + "."
        if short_name.endswith("-."):
            return short_name[:-2] + "."

        if short_name.endswith(" ."):
            return short_name[:-2]

        return short_name

    @property
    def day_passes_of_this_season(self):
        signups_of_this_season = (
            self.signups.filter(**{"training__date__gte": f"{now().year}-1-1"})
            .select_related("training")
            .prefetch_related("purchases")
        )
        purchases = [
            purchase
            for signup in signups_of_this_season
            for purchase in signup.purchases.all()
        ]
        return [purchase for purchase in purchases if purchase.is_day_pass]

    @property
    def has_bills(self):
        signups = self.signups.prefetch_related("bill")
        return any(signup.is_paid for signup in signups)

news/forms.py
from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.mail import send_mail

from .models import Pilot


class ContactForm(forms.Form):
    email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(required=True)

    # Spam protection
    name = forms.CharField(required=False)
    javascript = forms.CharField(required=False)

    def clean_name(self):
        name = self.cleaned_data.get("name")
        if name:
            raise ValidationError("Nachricht konnte nicht gesendet werden.")
        return name

    def clean_javascript(self):
        javascript = self.cleaned_data.get("javascript")
        if javascript != "JavaScript active":
            raise ValidationError("Du musst JavaScript aktivieren.")
        return javascript

    def send_mail(self):
        message = self.cleaned_data["message"] + "\n\n" + self.cleaned_data["email"]
        send_mail(
            subject="Kontaktformular: " + self.cleaned_data["subject"],
            message=message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[settings.INFO_EMAIL],
            fail_silently=False,
        )


class MembershipForm(forms.Form):
    street = forms.CharField(required=True)
    town = forms.CharField(required=True)
    country = forms.CharField(required=True)
    request_membership = forms.BooleanField(required=False)
    accept_statutes = forms.BooleanField(required=False)
    comment = forms.CharField(required=False)

    def clean_request_membership(self):
        request_membership = self.cleaned_data.get("request_membership")
        if not request_membership:
            raise ValidationError("Du musst Mitglied werden wollen.")
        return request_membership

    def clean_accept_statutes(self):
        accept_statutes = self.cleaned_data.get("accept_statutes")
        if not accept_statutes:
            raise ValidationError("Du musst mit unseren Statuten einverstanden sein.")
        return accept_statutes

    def send_mail(self):
        message = "\n".join(
            [
                str(self.sender),
                self.cleaned_data["street"],
                self.cleaned_data["town"],
                self.cleaned_data["country"],
                self.sender.email,
                self.sender.phone,
                "\nMöchte Mitglied werden.",
            ]
        )
        if day_passes := self.sender.day_passes_of_this_season:
            dates = ", ".join(
                str(day_pass.signup.training.date) for day_pass in day_passes
            )
            message += (
                f"\n\n{self.sender.first_name} hat diese Saison {len(day_passes)} "
                f"Tagesmitgliedschaft(en) bezahlt ({dates})."
            )
        if comment := self.cleaned_data["comment"]:
            message += "\n\nKommentar:\n" + comment
        send_mail(
            subject="Antrag ACBeo-Mitgliedschaft",
            message=message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[settings.INFO_EMAIL, self.sender.email],
            fail_silently=False,
        )


class PilotCreationForm(forms.ModelForm):
    accept_safety_concept = forms.BooleanField(required=False)
    password1 = forms.CharField()
    password2 = forms.CharField()

    # Spam protection
    username = forms.CharField(required=False)
    javascript = forms.CharField(required=False)

    class Meta:
        model = Pilot
        fields = ("first_name", "last_name", "email", "phone")

    def clean_accept_safety_concept(self):
        accept_safety_concept = self.cleaned_data.get("accept_safety_concept")
        if not accept_safety_concept:
            raise ValidationError(
                "Du musst mit unserem Sicherheitskonzept einverstanden sein."
            )
        return accept_safety_concept

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwörter müssen gleich sein.")
        return password2

    def clean_username(self):
        username = self.cleaned_data.get("username")
        if username:
            raise ValidationError("Konto konnte nicht angelegt werden.")
        return username

    def clean_javascript(self):
        javascript = self.cleaned_data.get("javascript")
        if javascript != "JavaScript active":
            raise ValidationError("Du musst JavaScript aktivieren.")
        return javascript

    def save(self, commit=True):
        pilot = super().save(commit=False)
        pilot.set_password(self.cleaned_data["password1"])
        if commit:
            pilot.save()
        return pilot


class PilotUpdateForm(forms.ModelForm):
    class Meta:
        model = Pilot
        fields = ("first_name", "last_name", "email", "phone")

    def send_mail(self):
        if not self.changed_data:
            return

        message = (
            f"{self.cleaned_data['first_name']} {self.cleaned_data['last_name']} hat "
            "folgende Änderungen am Konto gemacht:\n\n"
        )
        for field in self.changed_data:
            message += f"{field}: {self[field].initial} -> {self.cleaned_data[field]}\n"
        send_mail(
            subject="Änderung an Konto",
            message=message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[settings.INFO_EMAIL],
            fail_silently=False,
        )

news/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views import generic

from .forms import ContactForm, MembershipForm, PilotCreationForm, PilotUpdateForm
from .models import Post


class PostListView(generic.ListView):
    model = Post
    paginate_by = 3


class PostDetailView(generic.DetailView):
    model = Post


class ContactFormView(SuccessMessageMixin, generic.FormView):
    form_class = ContactForm
    template_name = "news/contact.html"
    success_url = reverse_lazy("home")
    success_message = "Nachricht abgesendet."

    def get_initial(self):
        initial = super(ContactFormView, self).get_initial()
        if self.request.user.is_authenticated:
            initial["email"] = self.request.user.email
        if subject := self.request.GET.get("subject"):
            initial["subject"] = subject
        return initial

    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)


class LoginForbiddenMixin(UserPassesTestMixin):
    def test_func(self):
        return not self.request.user.is_authenticated


class PilotCreateView(LoginForbiddenMixin, SuccessMessageMixin, generic.CreateView):
    form_class = PilotCreationForm
    template_name = "news/pilot_create.html"
    success_message = "Konto angelegt."

    def get_success_url(self):
        success_url = reverse_lazy("login")
        if next := self.request.GET.get("next"):
            success_url += f"?next={next}"
        return success_url


class PilotUpdateView(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    form_class = PilotUpdateForm
    template_name = "news/pilot_update.html"
    success_message = "Änderungen gespeichert."

    def get_object(self):
        return self.request.user

    def form_valid(self, form):
        if self.request.user.is_member:
            form.send_mail()
        return super().form_valid(form)

    def get_success_url(self):
        if success_url := self.request.GET.get("next"):
            return success_url

        return reverse_lazy("home")


class PilotPasswordResetView(SuccessMessageMixin, PasswordResetView):
    template_name = "news/password_reset.html"
    subject_template_name = "news/password_reset_subject.txt"
    email_template_name = "news/password_reset_email.html"
    success_url = reverse_lazy("home")
    success_message = (
        "Instruktionen zum Zurücksetzen des Passworts wurden an die angegebene Email "
        "geschickt."
    )


class PilotPasswordResetConfirmView(SuccessMessageMixin, PasswordResetConfirmView):
    template_name = "news/password_reset_confirm.html"
    success_url = reverse_lazy("login")
    success_message = "Passwort geändert."


class NonMemberOnlyMixin(LoginRequiredMixin, UserPassesTestMixin):
    def test_func(self):
        return not self.request.user.is_member


class MembershipFormView(NonMemberOnlyMixin, SuccessMessageMixin, generic.FormView):
    form_class = MembershipForm
    template_name = "news/membership.html"
    success_url = reverse_lazy("home")
    success_message = "Mitgliedschaft beantragt."

    def form_valid(self, form):
        form.sender = self.request.user
        form.send_mail()
        self.request.user.make_member()
        return super().form_valid(form)

news/templates/news/contact.html
{% extends "base.html" %}

{% block title %}Kontakt{% endblock title %}

{% block headline %}Kontakt{% endblock headline %}

{% block content %}

<div class="row mt-2">

    <div class="col left">
        <div class="card mb-4">
            <div class="card-body">
                <main class="form">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-floating md-3">
                            <input type="text" name="name" class="form-control" placeholder="text">
                            <label for="floatingInput">Leer lassen!</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="email" name="email" class="form-control" placeholder="text" 
                            {% if form.email.value %} value="{{ form.email.value }}" {% endif %} required>
                            <label for="floatingInput">Email</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="text" name="subject" class="form-control" placeholder="text"
                            {% if form.subject.value %} value="{{ form.subject.value }}" {% endif %} required>
                            <label for="floatingInput">Betreff</label>
                        </div>
                        <div class="form-floating mb-3">
                            <textarea class="form-control" placeholder="text" name="message" style="height: 200px"
                            {% if form.message.value %} value="{{ form.message.value }}" {% endif %} required></textarea>
                            <label for="message">Nachricht</label>
                        </div>
                        <input type="hidden" name="javascript" id="id_javascript">
                        <button class="btn btn-primary" type="submit">Absenden</button>
                        <a href="javascript:history.back()" class="btn btn-outline-dark">Abbrechen</a>
                    </form>
                </main>
            </div>
        </div>
    </div>

    {% include 'news/sidebar.html' %}
</div>

<script>
    document.getElementById("id_javascript").value = "JavaScript active"
</script>

{% endblock content %}

news/templates/news/index.html
{% extends "base.html" %}

{% block title %}News{% endblock title %}

{% block headline %}News{% endblock headline %}

{% block content %}

<div class="row mt-2">

    <div class="col left">
        {% for post in post_list %}
        <div class="card mb-4">
            <h5 class="card-header"><a href="{% url 'post' post.slug  %}">{{ post.title }}</a></h5>
            <div class="card-body">
                <h6 class="card-subtitle mb-2 text-muted">{{ post.author }} | {{ post.created_on.date }}</h6>
                <p class="card-text">{{ post.content | safe }}</p>
            </div>
        </div>
        {% endfor %}

        {% if is_paginated %}
        <ul class="pagination justify-content-center">
            <div class="btn-group">
                {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" type="button" class="btn btn-primary"><i
                        class="bi bi-chevron-double-left"></i></a>
                {% endif %}
                {% if page_obj.has_previous %}
                <a href="{% url 'home' %}" type="button" class="btn btn-primary">Anfang</a>
                <a href="?page={{ page_obj.previous_page_number }}" type="button" class="btn btn-primary"><i
                        class="bi bi-chevron-double-right"></i></a>
                {% endif %}
            </div>
        </ul>
        {% endif %}
    </div>

    {% include 'news/sidebar.html' %}
</div>

{% endblock content %}

news/templates/news/login.html
{% extends "base.html" %}

{% block title %}Anmelden{% endblock title %}

{% block headline %}Anmelden{% endblock headline %}

{% block content %}

<div class="col-md-4">
    <div class="card my-4">
        <div class="card-body">
            <main class="form-signin">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-floating mb-3">
                        <input type="text" name="username" class="form-control" placeholder="text">
                        <label for="floatingInput">Email</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" name="password" class="form-control" placeholder="password">
                        <label for="floatingPassword">Passwort</label>
                    </div>
                    <button class="btn btn-primary mb-2" type="submit">Anmelden</button>
                    <a href="javascript:history.back()" class="btn btn-outline-dark mb-2">Abbrechen</a>
                </form>
            </main>
            <a href="{% url 'register' %}?next={{ next }}">Noch kein Konto</a> oder <a href="{% url 'password_reset' %}">Passwort
                vergessen</a>?
        </div>
    </div>
</div>

{% endblock content %}

news/templates/news/password_reset.html
{% extends "base.html" %}

{% block title %}Passwort zurücksetzen{% endblock title %}

{% block headline %}Passwort zurücksetzen{% endblock headline %}

{% block content %}

<div class="col-md-4">
    <div class="card my-4">
        <div class="card-body">
            <main class="form">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-floating mb-3">
                        <input type="text" name="email" class="form-control" placeholder="text">
                        <label for="floatingInput">Email</label>
                    </div>
                    <button class="btn btn-primary mb-2" type="submit">Zurücksetzen</button>
                    <a href="{% url 'login' %}" class="btn btn-outline-dark mb-2">Abbrechen</a>
                </form>
            </main>
            <a href="{% url 'register' %}">Noch kein Konto</a>? 
        </div>
    </div>
</div>

{% endblock content %}

news/templates/news/password_reset_confirm.html
{% extends "base.html" %}

{% block title %}Passwort ändern{% endblock title %}

{% block headline %}Passwort ändern{% endblock headline %}

{% block content %}

<div class="col-md-4">
    <div class="card my-4">
        <div class="card-body">
            <main class="form">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-floating mb-3">
                        <input type="password" name="new_password1" class="form-control" placeholder="password">
                        <label for="floatingPassword">Neues Passwort</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" name="new_password2" class="form-control" placeholder="password">
                        <label for="floatingPassword">Passwort bestätigen</label>
                    </div>
                    <button class="btn btn-primary mb-2" type="submit">Passwort ändern</button>
                    <a href="{% url 'login' %}" class="btn btn-outline-dark mb-2">Abbrechen</a>
                </form>
            </main>
        </div>
    </div>
</div>

{% endblock content %}

news/templates/news/password_reset_email.html
{% autoescape off %}
Hallo {{ user.first_name }}

Um das Passwort von {{ user.email }} für {{ domain }} zurück zu setzen, bitte diesen Link verwenden:
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

Bitte ignoriere diese Nachricht, falls du dein Passwort nicht zurücksetzen willst.

Gruss
ACBeo
{% endautoescape %}

news/templates/news/pilot_create.html
{% extends "base.html" %}

{% block title %}Konto erstellen{% endblock title %}

{% block headline %}Konto erstellen{% endblock headline %}

{% block content %}

{% load static %}

<div class="col-md-4">
    <div class="card my-4">
        <div class="card-body">
            <main class="form">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-floating md-3">
                        <input type="text" name="username" class="form-control" placeholder="text">
                        <label for="floatingInput">Leer lassen!</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" name="first_name" class="form-control" placeholder="text"
                            {% if form.first_name.value %}value="{{ form.first_name.value }}"{% endif %}>
                        <label for="floatingInput">Vorname</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" name="last_name" class="form-control" placeholder="text"
                            {% if form.last_name.value %}value="{{ form.last_name.value }}"{% endif %}>
                        <label for="floatingInput">Nachname</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="email" name="email" class="form-control" placeholder="name@example.com"
                            {% if form.email.value %}value={{ form.email.value }}{% endif %}>
                        <label for="floatingInput">Email</label>
                        <small class="text-muted">Zum Anmelden und Passwort Zurücksetzen.</small>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="tel" name="phone" class="form-control" placeholder="text"
                            {% if form.phone.value %}value="{{ form.phone.value }}"{% endif %}>
                        <label for="floatingInput">Telefonnummer (z. B. 079 123 45 67)</label>
                        <small class="text-muted">Wir kontaktieren dich per Telefon, wenn wir z. B. spät ein Training
                            absagen müssen, und wir senden nach Rücksprache pro Training zwei Nummern von
                            Teilnehmenden an Notfalldienste.</small>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" name="password1" autocomplete="new-password" class="form-control"
                            placeholder="password">
                        <label for="floatingPassword">Passwort</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" name="password2" autocomplete="new-password" class="form-control"
                            placeholder="password">
                        <label for="floatingPassword">Passwort wiederholen</label>
                    </div>
                    <div class="form-check mb-3">
                        <input class="form-check-input" type="checkbox" name="accept_safety_concept"
                            id="acceptSafetyConcept" {% if form.accept_safety_concept.value %}checked{% endif %}>
                        <label class="form-check-label" for="acceptSafetyConcept">
                            Ich bin mit dem <a href="{% static 'news/sicherheitskonzept.pdf' %}">Sicherheitskonzept</a>
                            einverstanden.
                        </label>
                    </div>
                    <input type="hidden" name="javascript" id="id_javascript">
                    <button class="btn btn-primary mb-2" type="submit">Konto erstellen</button>
                    <a href="javascript:history.back()" class="btn btn-outline-dark mb-2">Abbrechen</a>
                </form>
            </main>
            Falls du bereits ein Konto hast, bitte <a href="{% url 'login' %}?next={{ next }}">einloggen</a>.
        </div>
    </div>
</div>

<script>
    document.getElementById("id_javascript").value = "JavaScript active"
</script>

{% endblock content %}

news/templates/news/post.html
{% extends 'base.html' %}

{% block title %}{{ post.title }}{% endblock title %}

{% block headline %}News{% endblock headline %}

{% block content %}

<div class="row">
    <div class="col-md-8 left">
        <div class="card mb-4">
            <div class="card-body">
                <h1>{{ post.title }}</h1>
                <p class="text-muted">{{ post.author }} | {{ post.created_on.date }}</p>
                <p class="card-text">{{ post.content | safe }}</p>
            </div>
        </div>
    </div>
    {% include 'news/sidebar.html' %}
</div>

{% endblock content %}

news/templates/news/register.html
{% extends "base.html" %}

{% block title %}Konto erstellen{% endblock title %}

{% block headline %}Konto erstellen{% endblock headline %}

{% block content %}

{% load static %}

<div class="col-md-4">
    <div class="card my-4">
        <div class="card-body">
            <main class="form">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-floating md-3">
                        <input type="text" name="username" class="form-control" placeholder="text">
                        <label for="floatingInput">Leer lassen!</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" name="first_name" class="form-control" placeholder="text"
                            {% if form.first_name.value %}value="{{ form.first_name.value }}"{% endif %}>
                        <label for="floatingInput">Vorname</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" name="last_name" class="form-control" placeholder="text"
                            {% if form.last_name.value %}value="{{ form.last_name.value }}"{% endif %}>
                        <label for="floatingInput">Nachname</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="email" name="email" class="form-control" placeholder="name@example.com"
                            {% if form.email.value %}value={{ form.email.value }}{% endif %}>
                        <label for="floatingInput">Email</label>
                        <small class="text-muted">Zum Anmelden und Passwort Zurücksetzen.</small>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="tel" name="phone" class="form-control" placeholder="text"
                            {% if form.phone.value %}value="{{ form.phone.value }}"{% endif %}>
                        <label for="floatingInput">Telefonnummer (z. B. 079 123 45 67)</label>
                        <small class="text-muted">Wir kontaktieren dich per Telefon, wenn wir z. B. spät ein Training
                            absagen müssen, und wir senden nach Rücksprache pro Training zwei Nummern von
                            Teilnehmenden an Notfalldienste.</small>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" name="password1" autocomplete="new-password" class="form-control"
                            placeholder="password">
                        <label for="floatingPassword">Passwort</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" name="password2" autocomplete="new-password" class="form-control"
                            placeholder="password">
                        <label for="floatingPassword">Passwort wiederholen</label>
                    </div>
                    <div class="form-check mb-3">
                        <input class="form-check-input" type="checkbox" name="accept_safety_concept"
                            id="acceptSafetyConcept">
                        <label class="form-check-label" for="acceptSafetyConcept">
                            Ich bin mit dem <a href="{% static 'news/sicherheitskonzept.pdf' %}">Sicherheitskonzept</a>
                            einverstanden.
                        </label>
                    </div>
                    <input type="hidden" name="javascript" id="id_javascript">
                    <button class="btn btn-primary mb-2" type="submit">Konto erstellen</button>
                    <a href="javascript:history.back()" class="btn btn-outline-dark mb-2">Abbrechen</a>
                </form>
            </main>
            Falls du bereits ein Konto hast, bitte <a href="{% url 'login' %}?next={{ next }}">einloggen</a>.
        </div>
    </div>
</div>

<script>
    document.getElementById("id_javascript").value = "JavaScript active"
</script>

{% endblock content %}