acbeo/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("trainings/", include("trainings.urls")),
    path("berichte/", include("bookkeeping.urls")),
    path("", include("news.urls")),
]

bookkeeping/urls.py
from django.urls import path, register_converter

from . import views
from trainings.urls import DateConverter


register_converter(DateConverter, "date")

urlpatterns = [
    path("", views.ReportListView.as_view(), name="reports"),
    path("<int:year>/", views.ReportListView.as_view(), name="reports"),
    path("bilanz/", views.BalanceView.as_view(), name="balance"),
    path("bilanz/<int:year>/", views.BalanceView.as_view(), name="balance"),
    path("pilotinnen/", views.PilotListView.as_view(), name="pilots"),
    path("pilotinnen/<int:year>/", views.PilotListView.as_view(), name="pilots"),
    path("erstellen/", views.ReportCreateView.as_view(), name="create_report"),
    path("<date:date>/", views.ReportUpdateView.as_view(), name="update_report"),
    path(
        "<date:date>/ausgabe-erfassen/",
        views.ExpenseCreateView.as_view(),
        name="create_expense",
    ),
    path(
        "<date:date>/ausgabe-bearbeiten/<int:pk>/",
        views.ExpenseUpdateView.as_view(),
        name="update_expense",
    ),
    path(
        "<date:date>/abschoepfen/",
        views.AbsorptionCreateView.as_view(),
        name="create_absorption",
    ),
    path(
        "<date:date>/abschoepfung-bearbeiten/<int:pk>/",
        views.AbsorptionUpdateView.as_view(),
        name="update_absorption",
    ),
    path("run-erstellen/", views.RunCreateView.as_view(), name="create_run"),
    path("run-bearbeiten/<int:run>/", views.RunUpdateView.as_view(), name="update_run"),
    path(
        "<date:date>/abos-abrechnen/",
        views.BillBatchCreateView.as_view(),
        name="batch_create_bills",
    ),
    path(
        "<date:date>/bezahlen/<int:signup>/",
        views.BillCreateView.as_view(),
        name="create_bill",
    ),
    path(
        "<date:date>/bezahlung-bearbeiten/<int:pk>/",
        views.BillUpdateView.as_view(),
        name="update_bill",
    ),
    path(
        "<date:date>/einkauf-erfassen/<int:signup>/",
        views.PurchaseCreateView.as_view(),
        name="create_purchase",
    ),
    path(
        "<date:date>/einkauf-entfernen/<int:pk>/",
        views.PurchaseDeleteView.as_view(),
        name="delete_purchase",
    ),
    path("twint/", views.TwintView.as_view(), name="twint"),
    path("meine-rechnungen/", views.BillListView.as_view(), name="bills"),
    path("meine-rechnungen/<int:year>/", views.BillListView.as_view(), name="bills"),
]

news/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views


urlpatterns = [
    path("", views.PostListView.as_view(), name="home"),
    path("kontakt/", views.ContactFormView.as_view(), name="contact"),
    path("registrieren/", views.PilotCreateView.as_view(), name="register"),
    path("mitglied-werden/", views.MembershipFormView.as_view(), name="membership"),
    path("anmelden/", LoginView.as_view(template_name="news/login.html"), name="login"),
    path("konto-bearbeiten/", views.PilotUpdateView.as_view(), name="update_pilot"),
    path("abmelden/", LogoutView.as_view(), name="logout"),
    path(
        "passwort-zuruecksetzen/",
        views.PilotPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "passwort-zuruecksetzen/<uidb64>/<token>/",
        views.PilotPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("<slug:slug>/", views.PostDetailView.as_view(), name="post"),
]

bookkeeping/models.py
from decimal import Decimal

from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.dispatch import receiver


class Report(models.Model):
    training = models.OneToOneField(
        "trainings.Training", on_delete=models.CASCADE, primary_key=True
    )
    cash_at_start = models.SmallIntegerField(validators=[MinValueValidator(0)])
    cash_at_end = models.SmallIntegerField(
        blank=True, null=True, validators=[MinValueValidator(0)]
    )
    orga_1 = models.ForeignKey(
        "trainings.Signup",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="reports_1",
    )
    orga_2 = models.ForeignKey(
        "trainings.Signup",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="reports_2",
    )
    remarks = models.CharField(max_length=300, default="", blank=True)

    def __str__(self):
        return f"{self.training}"

    @property
    def orgas(self):
        return [orga for orga in [self.orga_1, self.orga_2] if orga]

    @property
    def cash_revenue(self):
        bills = self.bills.all()
        return sum(bill.amount for bill in bills if bill.was_paid_in_cash)

    @property
    def other_revenue(self):
        bills = self.bills.all()
        return sum(bill.amount for bill in bills if not bill.was_paid_in_cash)

    @property
    def cash_expediture(self):
        expenses = sum(expense.amount for expense in self.expenses.all())
        absorptions = sum(absorption.amount for absorption in self.absorptions.all())
        return expenses + absorptions

    @property
    def difference(self):
        if self.cash_at_end:
            return self.cash_at_end - (
                self.cash_at_start + self.cash_revenue - self.cash_expediture
            )

    @property
    def num_unpaid_signups(self):
        return sum(signup.must_be_paid for signup in self.training.signups.all())

    @property
    def num_selected_signups(self):
        return sum(signup.is_selected for signup in self.training.signups.all())

    @property
    def num_runs(self):
        return len(set(run.created_on for run in self.runs.all()))


class Expense(models.Model):
    class Reasons(models.IntegerChoices):
        GAS = 0, "Tanken"
        PARKING = 1, "Parkkarte"
        STREET = 2, "Kleber Axalpstrasse"
        OTHER = 3, "Anderes (bitte angeben)"

    report = models.ForeignKey(
        Report, on_delete=models.CASCADE, related_name="expenses"
    )
    reason = models.CharField(max_length=50, blank=True)
    amount = models.SmallIntegerField(validators=[MinValueValidator(0)])

    @property
    def description(self):
        return self.reason


class PaymentMethods(models.IntegerChoices):
    CASH = 0, "Bar"
    BANK_TRANSFER = 1, "Überweisung"
    TWINT = 2, "TWINT"


class Absorption(models.Model):
    PAYMENT_CHOICES = [
        choice for choice in PaymentMethods.choices if choice[0] != PaymentMethods.CASH
    ]

    report = models.ForeignKey(
        Report, on_delete=models.CASCADE, related_name="absorptions"
    )
    signup = models.ForeignKey(
        "trainings.Signup", on_delete=models.CASCADE, related_name="absorptions"
    )
    reason = "Abschöpfung"
    amount = models.SmallIntegerField(validators=[MinValueValidator(0)])
    method = models.SmallIntegerField(choices=PAYMENT_CHOICES)

    @property
    def description(self):
        return f"Abschöpfung {self.signup.pilot}"


class Run(models.Model):
    Kind = models.IntegerChoices(
        "Kind", "FLIGHT BREAK BUS BOAT FLIGHT_WITH_POSTBUS FLIGHT_WITH_LIFT"
    )

    signup = models.ForeignKey(
        "trainings.Signup", on_delete=models.CASCADE, related_name="runs"
    )
    report = models.ForeignKey(Report, on_delete=models.CASCADE, related_name="runs")
    kind = models.SmallIntegerField(choices=Kind.choices)
    created_on = models.DateTimeField()

    class Meta:
        indexes = [models.Index(fields=["created_on"])]
        unique_together = (("signup", "report", "created_on"),)
        ordering = ("report", "created_on", "signup__pilot")

    def __str__(self):
        return f"{self.signup.pilot} {self.get_kind_display()} on {self.report}"

    @property
    def is_relevant_for_bill(self):
        return self.kind != self.Kind.BREAK

    @property
    def is_flight(self):
        return self.kind in (
            self.Kind.FLIGHT,
            self.Kind.FLIGHT_WITH_POSTBUS,
            self.Kind.FLIGHT_WITH_LIFT,
        )

    @property
    def with_bus(self):
        return self.kind == self.Kind.FLIGHT

    @property
    def with_lift(self):
        return self.kind == self.Kind.FLIGHT_WITH_LIFT

    @property
    def with_postbus(self):
        return self.kind == self.Kind.FLIGHT_WITH_POSTBUS

    @property
    def is_service(self):
        return self.kind in (self.Kind.BUS, self.Kind.BOAT)

    def save(self, *args, **kwargs):
        if self.signup.is_paid:
            raise ValidationError(f"{self.signup.pilot} hat bereits bezahlt.")
        super().save(*args, **kwargs)


class Bill(models.Model):
    PRICE_OF_FLIGHT = 9
    PAYMENT_CHOICES = [
        choice
        for choice in PaymentMethods.choices
        if choice[0] != PaymentMethods.BANK_TRANSFER
    ]

    signup = models.OneToOneField(
        "trainings.Signup", on_delete=models.CASCADE, related_name="bill"
    )
    report = models.ForeignKey(Report, on_delete=models.CASCADE, related_name="bills")
    # Rather than handing money out, we add extra services to pilot.prepaid_flights,
    # thus bill.prepaid_flights can be negative.
    prepaid_flights = models.DecimalField(max_digits=5, decimal_places=2)
    amount = models.DecimalField(
        max_digits=5, decimal_places=2, validators=[MinValueValidator(0)]
    )
    method = models.SmallIntegerField(choices=PAYMENT_CHOICES)

    class Meta:
        unique_together = (("signup", "report"),)

    def __str__(self):
        return f"Bill for {self.signup.pilot} on {self.signup.training}"

    @property
    def description(self):
        return f"Rechnung {self.signup.pilot}"

    @property
    def num_flights(self):
        runs = self.signup.runs.all()
        return len([run for run in runs if run.is_flight])

    @property
    def detailed_flights(self):
        if not self.num_flights:
            return "0"

        details = []
        if self.num_flights_with_bus:
            details.append(str(self.num_flights_with_bus) + "x🚐")
        if self.num_flights_with_lift:
            details.append(str(self.num_flights_with_lift) + "x🚡")
        if self.num_flights_with_postbus:
            details.append(str(self.num_flights_with_postbus) + "x📯")
        return str(self.num_flights) + " (" + ", ".join(details) + ")"

    @property
    def num_flights_with_bus(self):
        runs = self.signup.runs.all()
        return len([run for run in runs if run.with_bus])

    @property
    def costs_flights_with_bus(self):
        return self.num_flights_with_bus * self.PRICE_OF_FLIGHT

    @property
    def num_flights_with_lift(self):
        runs = self.signup.runs.all()
        return len([run for run in runs if run.with_lift])

    @property
    def costs_flights_with_lift(self):
        return self.num_flights_with_lift * self.PRICE_OF_FLIGHT / 2

    @property
    def num_flights_with_postbus(self):
        runs = self.signup.runs.all()
        return len([run for run in runs if run.with_postbus])

    @property
    def costs_flights_with_postbus(self):
        return 0

    @property
    def num_services(self):
        runs = self.signup.runs.all()
        num_services = len([run for run in runs if run.is_service])
        if self.signup.is_training_orga:
            num_services += 1
        return num_services

    @property
    def revenue_services(self):
        return self.num_services * self.PRICE_OF_FLIGHT

    @property
    def num_prepaid_flights(self):
        if self.prepaid_flights is not None:
            return self.prepaid_flights

        return min(
            self.num_flights_with_bus
            + self.num_flights_with_lift / 2
            - self.num_services,
            self.signup.pilot.prepaid_flights,
        )

    @property
    def costs_prepaid_flights(self):
        return self.num_prepaid_flights * self.PRICE_OF_FLIGHT

    @property
    def num_flights_to_pay(self):
        return (
            self.num_flights_with_bus
            + Decimal(self.num_flights_with_lift / 2)
            - self.num_services
            - Decimal(self.num_prepaid_flights)
        )

    @property
    def costs_flights_to_pay(self):
        assert 0 <= self.num_flights_to_pay, f"Negative flights to pay in ({self})"
        return self.num_flights_to_pay * self.PRICE_OF_FLIGHT

    @property
    def to_pay(self):
        purchases = self.signup.purchases.all()
        costs_purchases = sum(purchase.price for purchase in purchases)
        return self.costs_flights_to_pay + costs_purchases

    @property
    def was_paid_in_cash(self):
        return self.method == PaymentMethods.CASH


@receiver(models.signals.post_save, sender=Bill)
def pay_with_prepaid_flights_and_mark_not_new(sender, instance, created, **kwargs):
    if not created:
        return

    if instance.signup.pilot.is_new:
        instance.signup.pilot.is_new = False
        instance.signup.pilot.save()

    if not instance.prepaid_flights:
        return

    instance.signup.pilot.prepaid_flights -= instance.prepaid_flights
    instance.signup.pilot.save()


@receiver(models.signals.post_delete, sender=Bill)
def return_prepaid_flights(sender, instance, **kwargs):
    # Since this is even called in `create_bill` we don't mark pilots new when deleting
    # the last `Bill`.

    if not instance.prepaid_flights:
        return

    instance.signup.pilot.prepaid_flights += instance.prepaid_flights
    instance.signup.pilot.save()


class Purchase(models.Model):

bookkeeping/templates/bookkeeping/absorption_update.html
{% extends "base.html" %}

{% block title %}Abschöpfung bearbeiten{% endblock title %}

{% block headline %}Abschöpfung bearbeiten{% endblock headline %}

{% block content %}

<div class="row mt-2">
    <div class="col-xl-4 col-lg-5">
        <div class="card mb-4">
            <h5 class="card-header">Für {{ view.kwargs.date | date:"l, j. E" }}</h5>
            <div class="card-body">
                <main class="form">
                    <form method="post">
                        {% csrf_token %}
                        <div class="row mb-3">
                            <label class="col-6 col-form-label">Betrag</label>
                            <div class="col-6">
                                <input type="number" class="form-control" name="amount" value={{ form.amount.value }}>
                            </div>
                        </div>
                        <div class="mb-3">
                            <label>Abgeschöpft von</label>
                            {% for signup in form.signup %}
                            <div class="form-check">
                                {{ signup.tag }}
                                <label class="form-check-label" for="{{ signup.id_for_label }}">
                                    {{ signup.choice_label }}</label>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="mb-3">
                            <label>Zahlungsart</label>
                            {% for method in form.method %}
                            <div class="form-check">
                                {{ method.tag }}
                                <label class="form-check-label" for="{{ method.id_for_label }}">
                                    {{ method.choice_label }}
                                </label>
                            </div>
                            {% endfor %}
                            <small class="text-muted">Bitte nach Möglichkeit per Überweisung, da dort keine Gebühren
                                anfallen.</small>
                        </div>
                        <div class="d-grid gap-2 d-sm-block">
                            <button class="btn btn-primary" type="submit">Speichern</button>
                            <button class="btn btn-danger" type="submit" name="delete">Löschen</button>
                            <a href="{{ view.get_success_url }}" class="btn btn-outline-dark">Abbrechen</a>
                        </div>
                    </form>
                </main>
            </div>
        </div>
    </div>
    <div class="col float-right">
        {% include 'bookkeeping/bank_details.html' %}
    </div>
</div>

{% endblock content %}

bookkeeping/templates/bookkeeping/balance_reports.html
{% extends "base.html" %}

{% block title %}Abrechnung {{ year }}{% endblock title %}

{% block headline %}Abrechnung {{ year }}{% endblock headline %}

{% block content %}

<div class="row mt-2">

    <div class="col-md-4 left">
        <div class="card mb-4">
            <h5 class="card-header">Übersicht</h5>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-sm table-hover">
                        <tbody>
                            <tr>
                                <td>Berichte <a href="{% url 'reports' year=year %}" class="bi bi-pencil-square"></a></td>
                                <td>{{ num_reports }}</td>
                            </tr>
                            <tr>
                                <td>Runs</td>
                                <td>{{ num_runs }}</td>
                            </tr>
                            <tr>
                                <td>Flüge</td>
                                <td>{{ num_flights }}</td>
                            </tr>
                            <tr>
                                <td>Pilot·innen</td>
                                <td>{{ num_pilots }}</td>
                            </tr>
                            <tr>
                                <td>Letzter Kassenstand</td>
                                <td>{{ latest_cash }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-4 left">
        <div class="card mb-4">
            <h5 class="card-header">Einnahmen</h5>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-sm table-hover">
                        <thead>
                            <tr>
                                <th scope="col"></th>
                                {% for method in total_revenue.keys %}
                                <th scope="col">{{ method }}</th>
                                {% endfor %}
                            </tr>
                        </thead>
                        <tbody class="table-group-divider">
                            <tr>
                                <td>Tagesmitgliedschaften</td>
                                {% for amount in revenue_from_day_passes.values %}
                                <td>{{ amount }}</td>
                                {% endfor %}
                            </tr>
                            <tr>
                                <td>Material</td>
                                {% for amount in revenue_from_equipment.values %}
                                <td>{{ amount }}</td>
                                {% endfor %}
                            </tr>
                            <tr>
                                <td>Flüge</td>
                                {% for amount in revenue_from_flights.values %}
                                <td>{{ amount }}</td>
                                {% endfor %}
                            </tr>
                        </tbody>
                        <tfoot class="table-group-divider">
                            <td>Total</td>
                            {% for amount in total_revenue.values %}
                            <td>{{ amount }}</td>
                            {% endfor %}
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-4 left">
        <div class="card mb-4">
            <h5 class="card-header">Ausgaben</h5>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-sm table-hover">
                        <thead>
                            <tr>
                                <th scope="col"></th>
                                <th scope="col">Betrag</th>
                            </tr>
                        </thead>
                        <tbody class="table-group-divider">
                            {% for reason, expenses in expenses_by_reason.items %}
                            <tr>
                                <td>{{ reason }}</td>
                                <td>{{ expenses }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot class="table-group-divider">
                            <td>Total</td>
                            <td>{{ total_expenses }}</td>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-12 left">

        <div class="card mb-4">
            <h5 class="card-header">Ausgaben im Detail</h5>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-sm table-hover">
                        <thead>
                            <tr>
                                <th scope="col">Datum</th>
                                <th scope="col">Zweck</th>
                                <th scope="col">Betrag</th>
                            </tr>
                        </thead>
                        <tbody class="table-group-divider">
                            {% for expense in expense_list %}
                            <tr>
                                <td>{{ expense.report.training.date }}</td>
                                <td>{{ expense.reason }}</td>
                                <td>{{ expense.amount }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        {% if previous_year or next_year %}
        <ul class="pagination justify-content-center">
            <div class="btn-group">
                {% if previous_year %}
                <a href="{% url 'balance' year=previous_year %}" type="button" class="btn btn-primary"><i
                        class="bi bi-chevron-double-left"></i></a>
                {% endif %}
                {% if next_year %}
                <a href="{% url 'balance' %}" type="button" class="btn btn-primary">Aktuelles Jahr</a>
                <a href="{% url 'balance' year=next_year %}" type="button" class="btn btn-primary"><i
                        class="bi bi-chevron-double-right"></i></a>
                {% endif %}
            </div>
        </ul>
        {% endif %}

    </div>
</div>

{% endblock content %}

bookkeeping/templates/bookkeeping/bill_batch_create.html
{% extends "base.html" %}

{% block title %}Mit Abos abrechnen{% endblock title %}

{% block headline %}Mit Abos abrechnen{% endblock headline %}

{% block content %}

<div class="row mt-2">

    <div class="col-xl-4 col-lg-5">

        <div class="card mb-4">
            <div class="card-body">
                {% if abo_only_signups %}
                <p class="card-text">Die folgenden Pilot·innen können direkt mit ihren Abos abgerechnet werden:</p>
                <ul>
                    {% for signup in abo_only_signups %}
                    <li>{{ signup.pilot }}</li>
                    {% endfor %}
                </ul>
                {% else %}
                <p class="card-text">Es können keine Pilot·innen (mehr) mit ihren Abos abgerechnet werden.</p>
                {% endif %}
                <main class="form">
                    <form method="post">
                        {% csrf_token %}
                        <div class="d-grid gap-2 d-block">
                            {% if abo_only_signups %}
                            <button class="btn btn-secondary" type="submit">Abrechnen</button>
                            {% endif %}
                            <a href="{{ view.get_report_url }}" class="btn btn-outline-dark">Abbrechen</a>
                        </div>
                    </form>
                </main>
            </div>
        </div>
    </div>

    <div class="col float-right">
        {% include 'bookkeeping/explanations.html' %}
    </div>

</div>

{% endblock content %}

bookkeeping/templates/bookkeeping/bill_update.html
{% extends "base.html" %}

{% block title %}Abrechnung bearbeiten{% endblock title %}

{% block headline %}Abrechnung bearbeiten{% endblock headline %}

{% block content %}

{% load bill_extras %}

<div class="row mt-2">
    <div class="col-xl-4 col-lg-5">
        <div class="card mb-4">
            <h5 class="card-header">{{ bill.signup.pilot }} für {{ bill.report.training.date | date:"D., j. M." }}</h5>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-sm table-hover">
                        <thead>
                            <tr>
                                <th scope="col"></th>
                                <th scope="col">Anzahl</th>
                                <th scope="col" class="text-end">Betrag</th>
                            </tr>
                        </thead>
                        <tbody class="table-group-divider">
                            {% if bill.num_flights_with_bus %}
                            <tr>
                                <td>Flüge mit Clubbus 🚐</td>
                                <td>{{ bill.num_flights_with_bus }}</td>
                                <td class="text-end">{{ bill.costs_flights_with_bus | floatformat:"2u" }}</td>
                            </tr>
                            {% endif %}
                            {% if bill.num_flights_with_lift %}
                            <tr>
                                <td>Flüge mit Sessellift 🚡</td>
                                <td>{{ bill.num_flights_with_lift }}</td>
                                <td class="text-end">{{ bill.costs_flights_with_lift | floatformat:"2u" }}</td>
                            </tr>
                            {% endif %}
                            {% if bill.num_flights_with_postbus %}
                            <tr>
                                <td>Flüge mit Postauto 📯</td>
                                <td>{{ bill.num_flights_with_postbus }}</td>
                                <td class="text-end">{{ bill.costs_flights_with_postbus | floatformat:"2u" }}</td>
                            </tr>
                            {% endif %}
                            {% if bill.num_services %}
                            <tr>
                                <td>Dienste</td>
                                <td>{{ bill.num_services }}</td>
                                <td class="text-end">-{{ bill.revenue_services | floatformat:"2u" }}</td>
                            </tr>
                            {% endif %}
                            {% if 0 < bill.prepaid_flights %}
                            <tr>
                                <td>Mit Abo bezahlt</td>
                                <td>{{ bill.prepaid_flights }}</td>
                                <td class="text-end">-{{ bill.costs_prepaid_flights | floatformat:"2u" }}</td>
                            </tr>
                            {% elif bill.prepaid_flights < 0 %}
                            <tr>
                                <td>Flüge gutgeschrieben</td>
                                <td>{{ bill.num_prepaid_flights | abs | floatformat }}</td>
                                <td class="text-end">{{ bill.costs_prepaid_flights | abs | floatformat:"2u" }}</td>
                            </tr>
                            {% endif %}
                        </tbody>
                        {% if bill.signup.purchases.all %}
                        <tbody class="table-group-divider">
                            {% for purchase in bill.signup.purchases.all %}
                            <tr>
                                <td>{{ purchase.description }}</td>
                                    <td></td>
                                    <td class="text-end">{{ purchase.price | floatformat:"2u" }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                            {% endif %}
                        <tfoot class="table-group-divider">
                            <td>Zu bezahlen</td>
                            <td></td>
                            <td class="text-end">{{ bill.to_pay | floatformat:"2u" }}</td>
                        </tfoot>
                    </table>
                </div>
                <main class="form">
                    <form method="post">
                        {% csrf_token %}
                        <input type="hidden" name="prepaid_flights" value="{{ bill.prepaid_flights | floatformat:'u' }}">
                        <div class="mb-3">
                            <label>Zahlungsart</label>
                            {% for method in form.method %}
                            <div class="form-check">
                                {{ method.tag }}
                                <label class="form-check-label" for="{{ method.id_for_label }}">
                                    {{ method.choice_label }}
                                </label>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="form-floating mb-3">
                            <input type="number" min="{{ bill.to_pay }}" name="amount" class="form-control"
                                placeholder="text" value="{{ form.amount.value | floatformat:'u' }}">
                            <label>Betrag</label>
                        </div>
                        <div class="mb-3">Um Runs oder Einkäufe zu bearbeiten, muss die Abrechnung gelöscht werden.</div>
                        <div class="d-grid gap-2 d-sm-block">
                            <button class="btn btn-primary" type="submit">Speichern</button>
                            <button class="btn btn-danger" type="submit" name="delete">Löschen</button>
                            <a href="{{ view.get_report_url }}" class="btn btn-outline-dark">Abbrechen</a>
                        </div>
                    </form>
                </main>
            </div>
        </div>
    </div>

    <div class="col float-right">
        {% include 'bookkeeping/explanations.html' %}
    </div>

</div>

{% endblock content %}