acbeo/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("trainings/", include("trainings.urls")),
    path("berichte/", include("bookkeeping.urls")),
    path("", include("news.urls")),
]

news/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views


urlpatterns = [
    path("", views.PostListView.as_view(), name="home"),
    path("kontakt/", views.ContactFormView.as_view(), name="contact"),
    path("registrieren/", views.PilotCreateView.as_view(), name="register"),
    path("mitglied-werden/", views.MembershipFormView.as_view(), name="membership"),
    path("anmelden/", LoginView.as_view(template_name="news/login.html"), name="login"),
    path("konto-bearbeiten/", views.PilotUpdateView.as_view(), name="update_pilot"),
    path("abmelden/", LogoutView.as_view(), name="logout"),
    path(
        "passwort-zuruecksetzen/",
        views.PilotPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "passwort-zuruecksetzen/<uidb64>/<token>/",
        views.PilotPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("<slug:slug>/", views.PostDetailView.as_view(), name="post"),
]

trainings/urls.py
from datetime import datetime

from django.urls import path, register_converter
from django.views.generic import TemplateView

from . import views


class DateConverter:
    regex = "\d{4}-\d{2}-\d{2}"

    def to_python(self, value):
        return datetime.fromisoformat(value).date()

    def to_url(self, value):
        return value


register_converter(DateConverter, "date")

urlpatterns = [
    path("", views.TrainingListView.as_view(), name="trainings"),
    path(
        "infos/",
        TemplateView.as_view(template_name="trainings/about.html"),
        name="about_trainings",
    ),
    path("erstellen/", views.TrainingCreateView.as_view(), name="create_trainings"),
    path(
        "<date:date>/ansagen/",
        views.TrainingUpdateView.as_view(),
        name="update_training",
    ),
    path(
        "<date:date>/seepolizeimail/",
        views.EmergencyMailView.as_view(),
        name="emergency_mail",
    ),
    path("meine-trainings/", views.SignupListView.as_view(), name="signups"),
    path("einschreiben/", views.SignupCreateView.as_view(), name="signup"),
    path("<date:date>/einschreiben/", views.SignupCreateView.as_view(), name="signup"),
    path(
        "<date:date>/bearbeiten/",
        views.SignupUpdateView.as_view(),
        name="update_signup",
    ),
]

news/models.py
from django.conf import settings
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.utils.timezone import now


class Post(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="posts"
    )
    content = models.TextField()
    created_on = models.DateTimeField(default=now)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title


class PilotManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError("Pilot must have an email address")

        pilot = self.model(email=self.normalize_email(email))

        pilot.set_password(password)
        pilot.save()
        return pilot

    def create_superuser(self, email, password=None):
        pilot = self.create_user(
            email,
            password=password,
        )
        pilot.role = Pilot.Role.STAFF
        pilot.save()
        return pilot


def validate_phone(phone):
    for character in phone:
        if character not in "0123456789+() ":
            raise ValidationError(
                f"{phone} ist keine Telefonnummer.", params={"phone": phone}
            )


class Pilot(AbstractBaseUser):
    Role = models.IntegerChoices("Role", "GUEST MEMBER ORGA STAFF")

    email = models.EmailField(max_length=255, unique=True)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    phone = models.CharField(max_length=20, validators=[validate_phone])
    date_joined = models.DateTimeField(auto_now_add=True)
    role = models.IntegerField(choices=Role.choices, default=Role.GUEST)
    prepaid_flights = models.DecimalField(
        max_digits=5, decimal_places=2, validators=[MinValueValidator(0)], default=0
    )
    is_new = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)

    objects = PilotManager()

    USERNAME_FIELD = "email"

    class Meta:
        ordering = ["first_name", "last_name"]

    def __str__(self):
        return self.first_name + " " + self.last_name

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def make_member(self):
        self.role = self.Role.MEMBER
        self.save()

    @property
    def is_member(self):
        return self.role >= self.Role.MEMBER

    @property
    def is_orga(self):
        return self.role >= self.Role.ORGA

    @property
    def is_staff(self):
        return self.role == self.Role.STAFF

    @property
    def short_name(self):
        MAX_LENGTH = 15
        if len(name := str(self)) <= MAX_LENGTH:
            return name

        first, *middle_names, last = name.split()
        for i, name in enumerate(middle_names):
            if name in ["von", "Von"]:
                middle_names[i] = "v."
        
        short_name = " ".join([first] + middle_names + [last])
        if len(short_name) <= MAX_LENGTH:
            return short_name
        
        short_name = short_name[:MAX_LENGTH - 1] + "."
        if short_name.endswith("-."):
            return short_name[:-2] + "."

        if short_name.endswith(" ."):
            return short_name[:-2]

        return short_name

    @property
    def day_passes_of_this_season(self):
        signups_of_this_season = (
            self.signups.filter(**{"training__date__gte": f"{now().year}-1-1"})
            .select_related("training")
            .prefetch_related("purchases")
        )
        purchases = [
            purchase
            for signup in signups_of_this_season
            for purchase in signup.purchases.all()
        ]
        return [purchase for purchase in purchases if purchase.is_day_pass]

    @property
    def has_bills(self):
        signups = self.signups.prefetch_related("bill")
        return any(signup.is_paid for signup in signups)

trainings/models.py
from datetime import datetime, timedelta

from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone

from bookkeeping.models import Purchase


class Training(models.Model):
    date = models.DateField(unique=True)
    max_pilots = models.PositiveSmallIntegerField(
        default=11,
        blank=False,
        null=False,
        validators=[MinValueValidator(6), MaxValueValidator(33)],
    )
    min_orgas = 2
    priority_date = models.DateField(
        default=datetime.fromisoformat("2010-04-09").date()
    )
    info = models.CharField(max_length=300, default="", blank=True)
    emergency_mail_sender = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_DEFAULT,
        default=None,
        blank=True,
        null=True,
        db_index=False,
    )

    class Meta:
        indexes = [models.Index(fields=["date"])]
        ordering = ["date"]

    def __str__(self):
        return f"{self.date}"

    def pilots(self):
        return [signup.pilot for signup in self.signups.all()]

    @property
    def selected_signups(self):
        self.select_signups()
        return [
            signup
            for signup in self.signups.all().order_by("pilot")
            if signup.is_selected
        ]

    @property
    def active_signups(self):
        self.select_signups()
        return [
            signup
            for signup in self.signups.all()
            .prefetch_related("pilot")
            .prefetch_related("bill")
            .order_by("pilot")
            if signup.is_active
        ]

    @property
    def number_of_motivated_pilots(self):
        return sum(signup.is_motivated for signup in self.signups.all())

    @property
    def new_pilots(self):
        return [signup.pilot for signup in self.active_signups if signup.pilot.is_new]

    def select_signups(self):
        signups = self.signups.all()

        selected_orgas = [signup for signup in signups if signup.is_selected_orga]
        spots_for_orgas = max(0, self.min_orgas - len(selected_orgas))
        if spots_for_orgas:
            waiting_orgas = [signup for signup in signups if signup.is_waiting_orga]
            orgas_to_select = waiting_orgas[:spots_for_orgas]
            signups = orgas_to_select + [
                signup for signup in signups if signup not in orgas_to_select
            ]
            spots_for_orgas -= len(orgas_to_select)

        if timezone.now().date() <= self.priority_date:
            signups = [signup for signup in signups if signup.has_priority]

        for signup in signups[: self.max_pilots - spots_for_orgas]:
            signup.select()


class Signup(models.Model):
    Status = models.IntegerChoices("Status", "SELECTED WAITING CANCELED")
    Duration = models.IntegerChoices(
        "Duration", "ALL_DAY ARRIVING_LATE LEAVING_EARLY INDIVIDUALLY"
    )

    pilot = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="signups"
    )
    training = models.ForeignKey(
        Training, on_delete=models.CASCADE, related_name="signups"
    )
    status = models.SmallIntegerField(choices=Status.choices, default=Status.WAITING)
    signed_up_on = models.DateTimeField(auto_now_add=True)
    is_certain = models.BooleanField(default=True)
    duration = models.SmallIntegerField(
        choices=Duration.choices, default=Duration.ALL_DAY
    )
    for_sketchy_weather = models.BooleanField(default=True)
    comment = models.CharField(max_length=150, default="", blank=True)

    class Meta:
        indexes = [models.Index(fields=["status"])]
        unique_together = (("pilot", "training"),)
        ordering = ["status", "signed_up_on"]

    def __str__(self):
        return f"{self.pilot} {self.get_status_display()} for {self.training}"

    @property
    def is_motivated(self):
        return (
            self.status != self.Status.CANCELED
            and self.is_certain
            and self.duration == self.Duration.ALL_DAY
        )

    @property
    def has_priority(self):
        return (
            self.pilot.is_member
            and self.is_certain
            and self.duration == self.Duration.ALL_DAY
        )

    @property
    def is_selected(self):
        return self.status == self.Status.SELECTED

    @property
    def is_selected_orga(self):
        return self.status == self.Status.SELECTED and self.pilot.is_orga

    @property
    def is_waiting_orga(self):
        return self.status == self.Status.WAITING and self.pilot.is_orga

    @property
    def is_cancelable(self):
        if self.purchases.all():
            return False

        runs = self.runs.all()
        return not any(run.is_relevant_for_bill for run in runs)

    @property
    def is_active(self):
        return self.is_selected and not self.is_paid

    @property
    def must_be_paid(self):
        return not self.is_cancelable and not self.is_paid

    @property
    def is_training_orga(self):
        return self in {self.training.report.orga_1, self.training.report.orga_2}

    @property
    def needs_day_pass(self):
        if self.pilot.is_member:
            return False

        num_flights = len([run for run in self.runs.all() if run.is_flight])
        if num_flights < 3:
            return False

        day_passes_of_season = (
            Purchase.objects.filter(
                signup__pilot=self.pilot,
                signup__training__date__year=self.training.date.year,
                description=Purchase.DAY_PASS_DESCRIPTION,
            )
            .select_related("signup")
            .prefetch_related("signup__training")
        )
        if 4 <= len(day_passes_of_season):
            return False

        day_passes_of_last_month = [
            day_pass
            for day_pass in day_passes_of_season
            if (self.training.date - timedelta(days=31)) < day_pass.signup.training.date
        ]
        if 2 <= len(day_passes_of_last_month):
            return False

        if self in [day_pass.signup for day_pass in day_passes_of_last_month]:
            return False

        return True

    @property
    def is_paid(self):
        return hasattr(self, "bill")

    def select(self):
        if self.status != self.Status.WAITING:
            return
        self.status = self.Status.SELECTED
        self.save()

    def cancel(self):
        assert self.is_cancelable, f"Trying to cancel {self} relevant for billing!"
        self.signed_up_on = timezone.now()
        self.status = self.Status.CANCELED
        # Not saving, because called before saving updates from form

    def resignup(self):
        self.signed_up_on = timezone.now()
        self.status = self.Status.WAITING
        # Not saving, because called before saving updates from form

    def update_is_certain(self, new_is_certain):
        if self.is_certain == new_is_certain:
            return
        self.is_certain = new_is_certain
        if new_is_certain:
            return
        self.signed_up_on = timezone.now()
        self.status = self.Status.WAITING
        # Not saving, because called before saving updates from form

    def update_duration(self, new_duration):
        if self.duration == new_duration:
            return
        old_duration, self.duration = self.duration, new_duration
        if new_duration == self.Duration.ALL_DAY:
            return
        if old_duration != self.Duration.ALL_DAY:
            return
        self.signed_up_on = timezone.now()
        self.status = self.Status.WAITING
        # Not saving, because called before saving updates from form

trainings/templates/trainings/about.html
{% extends "base.html" %}

{% block title %}Praktische Informationen{% endblock title %}

{% block headline %}Praktische Informationen{% endblock headline %}

{% block content %}

<div class="row mt-2">
    
    <div class="col left">
        {% include 'trainings/infos.html' %}
        {% include 'trainings/rules.html' %}
    </div>
    
    {% include 'news/sidebar.html' %}

</div>

{% endblock content %}

trainings/templates/trainings/create_trainings.html
{% extends "base.html" %}

{% block title %}Trainings erstellen{% endblock title %}

{% block headline %}Trainings erstellen{% endblock headline %}

{% block content %}

<div class="col-xl-4 col-lg-5">
    <div class="card my-4">
        <div class="card-body">
            <p>Normale Trainings werden automatisch erstellt, sobald sich jemand einschreibt. Hier können
                mehrere Trainings auf einmal erstellt und z. B. mit der Information "Axalpwochen" versehen
                werden, ohne dass sich jemand einschreiben muss.</p>
            <p>Einstellungen bestehender Trainings (weil sich z. B. bereits jemand eingeschrieben hat) werden
                überschrieben, Anmeldungen bleiben erhalten.</p>
            <main class="form">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-floating mb-3">
                        <input type="date" class="form-control" name="first_day"
                            value="{{ form.first_day.value.isoformat }}" required>
                        <label>Erster Tag</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="date" class="form-control" name="last_day"
                            value="{{ form.last_day.value.isoformat }}" required>
                        <label>Letzter Tag</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" name="info" id="info" class="form-control" placeholder="text"
                            value="{{ form.info.value }}">
                        <label for="floatingInput">Infos</label>
                    </div>
                    <div class="row mb-3">
                        <label class="col-6 col-form-label">Max. Pilot·innen</label>
                        <div class="col-6">
                            <input type="number" class="form-control" name="max_pilots" value={{ form.max_pilots.value }}>
                        </div>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="date" class="form-control" name="priority_date"
                            value="{{ form.priority_date.value.isoformat }}" required>
                        <label>Datum Vorrang (bis und mit)</label>
                    </div>
                    <button class="btn btn-primary" type="submit">Speichern</button>
                    <input type="hidden" name="next" value="{{ next }}">
                    <a href="javascript:history.back()" class="btn btn-outline-dark">Abbrechen</a>
                </form>
            </main>
        </div>
    </div>
</div>

{% endblock content %}

trainings/templates/trainings/list_signups.html
{% extends "base.html" %}

{% block title %}Meine Trainings{% endblock title %}

{% block headline %}Meine Trainings{% endblock headline %}

{% block content %}

<div class="row mt-2">

    <div class="col-md-12 left">

        {% if signup_list %}

        <div class="card mb-4">
            <h5 class="card-header">Kommende Trainings</h5>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-sm table-hover">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Datum</th>
                                <th scope="col">Pilot·innen</th>
                                <th scope="col">Status</th>
                                <th scope="col">Verbindlichkeit</th>
                                <th scope="col">Zeitplan</th>
                                <th scope="col">Wetterwunsch</th>
                                <th scope="col" style="min-width: 300px">Trainingsinfo</th>
                                <th scope="col" style="min-width: 300px">Kommentar</th>
                            </tr>
                        </thead>
                        <tbody class="table-group-divider">
                            {% for signup in signup_list %}
                            <tr {% if signup.get_status_display == 'Canceled' %}class="text-muted"{% endif %}>
                                <td>{{ forloop.counter }}</td>
                                <td class="text-nowrap">{{ signup.training.date | date:"D., j. M. Y" }}
                                    {% if time == "future" %}
                                    <a href="{% url 'update_signup' date=signup.training.date.isoformat %}?next={% url 'signups' %}"
                                        class="bi bi-pencil-square" /a>
                                        {% endif %}
                                </td>
                                <td>
                                    {% if signup.training.number_of_motivated_pilots < 6 %}
                                    <span class="text-warning">{{ signup.training.number_of_motivated_pilots }} zu 100%</span>
                                    {% else %}
                                    {{ signup.training.number_of_motivated_pilots }} zu 100%
                                    {% endif %}
                                </td>
                                <td>
                                    {% if signup.get_status_display == 'Selected' %}<i
                                    class="bi bi-cloud-check text-success"></i>{% endif %}
                                    {% if signup.get_status_display == 'Waiting' %}<i
                                    class="bi bi-hourglass-split text-warning"></i>{% endif %}
                                    {% if signup.get_status_display == 'Canceled' %}<i
                                    class="bi bi-x-octagon text-danger"></i>{% endif %}
                                </td>
                                <td>
                                    {% if signup.get_status_display != 'Canceled' %}
                                    {% if signup.is_certain %}100%{% else %}<span class="text-warning">75%</span>{% endif %}
                                    {% endif %}
                                </td>
                                <td class="text-nowrap">
                                    {% if signup.for_time == signup.Time.WholeDay %}Ganzer Tag{% endif %}
                                    {% if signup.for_time == signup.Time.ArriveLate %}<span class="text-warning">Komme später</span>{% endif %}
                                    {% if signup.for_time == signup.Time.LeaveEarly %}<span class="text-warning">Gehe früher</span>{% endif %}
                                    {% if signup.for_time == signup.Time.Individually %}<span class="text-warning">Individuell</span>{% endif %}
                                </td>
                                <td>
                                    {% if signup.get_status_display != 'Canceled' %}
                                    {% if signup.for_sketchy_weather %}
                                    <i class="bi bi-cloud-haze2-fill"></i>
                                    {% else %}
                                    <i class="bi bi-sun"></i>
                                    {% endif %}
                                    {% endif %}
                                </td>
                                <td>{{ signup.training.info | safe }}</td>
                                <td>{{ signup.comment }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        {% else %}
    
        <p>Du bist für kein kommendes Training eingeschrieben.</p>
        <a href="{% url 'signup' %}" class="btn btn-secondary">Einschreiben</a>
    
        {% endif %}

    </div>

</div>


{% endblock content %}

trainings/templates/trainings/list_trainings.html
{% extends "base.html" %}

{% block title %}Trainings{% endblock title %}

{% block headline %}Nächste Trainings{% endblock headline %}

{% block content %}

<div class="row mt-2">

    <div class="col left">

        {% for training in training_list %}
        <div class="card mb-4" id="training_{{ forloop.counter }}">
            <h5 class="card-header">{{ training.date | date:"l, j. M." }} 
                {% if request.user.is_orga %}
                <a href="{% url 'update_training' date=training.date.isoformat %}?page={{ page_obj.number }}&training={{ forloop.counter }}"
                    class="bi bi-pencil-square"></a>
                    {% if training.date <= day_after_tomorrow %}
                        {% if not training.emergency_mail_sender %}
                        <a href="{% url 'emergency_mail' date=training.date.isoformat %}" class="text-danger bi bi-envelope-exclamation"></a>
                        {% else %}
                        <i class="text-muted bi bi-envelope-exclamation"></i>
                        {% endif %}
                    {% endif %}
                    {% if training.date == today %}
                    <a href="{% url 'create_report' %}" class="bi bi-clipboard"></a>
                    {% endif %}
                {% endif %}
            </h5>
            <div class="card-body">
                {% if training.info %}
                <p class="card-text">{{ training.info }}</p>
                {% endif %}
                <div class="table-responsive">
                    <table class="table table-sm table-hover">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Pilot·in</th>
                                <th scope="col">Status</th>
                                <th scope="col">Rolle</th>
                                <th scope="col">Einschreibedatum</th>
                                <th scope="col">Verbindlichkeit</th>
                                <th scope="col">Zeitplan</th>
                                <th scope="col">Wetterwunsch</th>
                                <th scope="col" style="min-width: 300px">Kommentar</th>
                            </tr>
                        </thead>
                        <tbody class="table-group-divider">
                            {% for signup in training.signups.all %}
                            <tr {% if signup.get_status_display == 'Canceled' %}class="text-muted"{% endif %}>
                                <td>{{ forloop.counter }}</td>
                                <td class="text-nowrap">{{ signup.pilot }}
                                    {% if signup.pilot == request.user %}
                                    <a href="{% url 'update_signup' date=training.date.isoformat %}?next={% url 'trainings' %}&page={{ page_obj.number }}&training={{ forloop.parentloop.counter }}"
                                        class="bi bi-pencil-square" />
                                    {% endif %}
                                </td>
                                <td>
                                    {% if signup.get_status_display == 'Selected' %}
                                    <i class="bi bi-cloud-check text-success"></i>
                                    {% elif signup.get_status_display == 'Waiting' %}
                                    <i class="bi bi-hourglass-split text-warning"></i>
                                    {% else %}
                                    <i class="bi bi-x-octagon text-danger"></i>
                                    {% endif %}
                                </td>
                                <td>
                                    {% if signup.pilot.get_role_display == 'Guest' %}
                                    Gast
                                    {% elif signup.pilot.get_role_display == 'Member' %}
                                    Mitglied
                                    {% else %}
                                    Leiter·in
                                    {% endif %}
                                </td>
                                <td class="text-nowrap">{{ signup.signed_up_on | date:"D., j. M. G:i" }}</td>
                                <td>
                                    {% if signup.get_status_display != 'Canceled' %}
                                        {% if signup.is_certain %}100%{% else %}<span class="text-warning">75%</span>{% endif %}
                                    {% endif %}
                                </td>
                                <td class="text-nowrap">
                                    {% if signup.get_status_display != 'Canceled' %}
                                        {% if signup.for_time == signup.Time.WholeDay %}Ganzer Tag{% endif %}
                                        {% if signup.for_time == signup.Time.ArriveLate %}<span class="text-warning">Kommt später</span>{% endif %}
                                        {% if signup.for_time == signup.Time.LeaveEarly %}<span class="text-warning">Geht früher</span>{% endif %}
                                        {% if signup.for_time == signup.Time.Individually %}<span class="text-warning">Individuell</span>{% endif %}
                                    {% endif %}
                                </td>
                                <td>
                                    {% if signup.get_status_display != 'Canceled' %}
                                        {% if signup.for_sketchy_weather %}
                                            <i class="bi bi-cloud-haze2-fill"></i>
                                        {% else %}
                                            <i class="bi bi-sun"></i>
                                        {% endif %}
                                    {% endif %}
                                </td>
                                <td>{{ signup.comment }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% if not request.user in training.pilots %}
                <a href="{% url 'signup' date=training.date.isoformat %}?&page={{ page_obj.number }}&training={{ forloop.counter }}"
                    class="btn btn-secondary mt-3">Einschreiben</a>
                {% endif %}
            </div>
        </div>
        {% endfor %}

        {% if not training_list %}
        <p>Im Moment ist niemand für ein kommendes Training eingeschrieben.</p>
        <a href="{% url 'signup' %}" class="btn btn-secondary">Einschreiben</a>
        {% else %}
        <p>Du kannst dich auch direkt für einen beliebigen Tag <a href="{% url 'signup' %}">einschreiben</a>.</p>
        {% endif %}

        {% if is_paginated %}
        <ul class="pagination justify-content-center">
            <div class="btn-group mb-2">
                {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}" type="button" class="btn btn-primary"><i
                        class="bi bi-chevron-double-left"></i></a>
                <a href="{% url 'trainings' %}" type="button" class="btn btn-primary">Nächste Trainings</a>
                {% endif %}

                {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" type="button" class="btn btn-primary"><i
                        class="bi bi-chevron-double-right"></i></a>
                {% endif %}
            </div>
        </ul>
        {% endif %}

    </div>
</div>

{% endblock content %}